name: ItemRestrict
main: net.craftersland.itemrestrict.ItemRestrict
version: 2.5.0
author: CraftersLand
load: POSTWORLD
website: www.craftersland.net
description: Item Restrict system.
api-version: 1.12
commands:
    itemrestrict:
        description: Main command.
permissions:
    ItemRestrict.admin:
        description: Bypass restrictions and access to reload command.
        default: op
    ItemRestrict.bypass:
        description: Bypass restrictions.
        default: false
